quiz/urls.py
from django.urls import path

from . import views
urlpatterns = [
    # path('', views.index, name='quiz_index'),
    path('about/', views.about, name='quiz_about'),
    path('', views.home, name='quiz_home'),
    path('take_quiz/', views.take_quiz, name='take_quiz'),
    path('quiz/', views.quiz, name='quiz'),
    path('api/get-quiz/', views.get_quiz, name='get_quiz')
]

quiz_project/urls.py
from django.contrib import admin

from django.contrib.auth import views as auth_views

from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name = 'register'),
    path('profile/', user_views.profile, name = 'profile'),
    path('login/', auth_views.LoginView.as_view(template_name = 'users/login.html'), name = 'login'),
    path('logout/', auth_views.LogoutView.as_view(template_name = 'users/logout.html'), name = 'logout'),
    path('', include('quiz.urls')),
    path('', include('quizes.urls', namespace='quizes'))
]
#adds url only if we are in debug mode
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

quizes/urls.py
from django.urls import path

# from .views import (
#     QuizListView,
#     QuizDetailView,
#     # quiz_detail_data_view,
#     # save_quiz_view
# )
from . import views

app_name = 'quizes'

urlpatterns = [
    # path('take_quiz/test', QuizListView.as_view(), name='quiz_list_view'),
    path('quiz_list/', views.QuizListView.as_view(), name='quiz_list_view'),
    path('quiz_list/quiz/<pk>', views.QuizDetailView.as_view(), name='quiz_view'),
    path('quiz_list/quiz/<pk>/data',views.quiz_detail_data_view, name='quiz_data_view'),
    path('quiz_list/quiz/<pk>/save', views.save_quiz_view, name='quiz_save_view'),
    path('quiz_list/upload/', views.upload_quiz, name='upload_quiz'),
]

quiz/models.py
from django.db import models
import uuid
import random

from operator import mod
from pyexpat import model
from django.db import models
from quizes.models import Quiz

# Create your models here.

# Base model to reduce repeatition of code.
class BaseModel(models.Model):
   uid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
   created_at = models.DateField(auto_now_add=True) 
   updated_at = models.DateField(auto_now=True)
   
   # While migration, we don't want to register this model as a table in our DB, we want to use this as a Class.
   class Meta:
       abstract = True  # this register BaseModel as a base class.
   
class Category(BaseModel):
    category_name = models.CharField(max_length=100)
    
    def __str__(self):
        return self.category_name
    
    

# related_name allows to have a reverse relationship between models
class Question(BaseModel):
    
    category = models.ForeignKey(Category, related_name='category', on_delete=models.CASCADE)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="questions", null=True)
    question = models.CharField(max_length=100)
    marks = models.IntegerField(default=5)
    
    def __str__(self):
        return self.question
    
    def get_ans(self):
        # this creates a list of the answers
        answer_objs = list(Answer.objects.filter(question=self)) # converted into a list to allow shuffling
        random.shuffle(answer_objs)
        data = []
        for answer_obj in answer_objs:
            data.append({
                'answer': answer_obj.answer,
                'is_correct': answer_obj.is_correct
            })
        return data
    
    # text = models.TextField()
    
    # def __str__(self):
    #     """
    #     How the Question is displayed in the Admin page
    #     """
    #     return f"{self.pk} - {str(self.text)[:10]}"

    # @property
    # def get_answers(self):
    #     return self.answers.all()
    
    

class Answer(BaseModel):
    question = models.ForeignKey(Question, related_name='question_answer', on_delete=models.CASCADE)
    answer = models.CharField(max_length=100)
    # text = models.TextField()
    is_correct = models.BooleanField(default=False)
    quiz = models.ForeignKey(Quiz, on_delete=models.CASCADE, related_name="answers", null=True)
    
    
    def __str__(self):
        return self.answer
    
    # question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name="answers")

    # def __str__(self):
        # return f"Question: {str(self.question.text)[:15]}, Ans: {str(self.text)[:10]}, Correct: {self.correct}"
    
    
    
    
# make sure to register the models in admin.py

'''
1. Add a category
2. Add questions
3. Add Answer to that question
'''

quizes/forms.py
from django import forms

class UploadCSVForm(forms.Form):
    csv_file = forms.FileField()

quiz/views.py
from django.shortcuts import render, redirect
from .models import *
from quizes.models import *
from django.http import HttpResponse, JsonResponse
import random

# Quiz API - Shuffles questions
def get_quiz(request):
    try:
        question_objs = Question.objects.all()
        data = []
        if request.GET.get('category'):
            question_objs = question_objs.filter(category__category_name__icontains=request.GET.get('category'))
        
        question_objs = list(question_objs)
        
        random.shuffle(question_objs) #allows us to select random questions
        for question_obj in question_objs:
            data.append({
                "category": question_obj.category.category_name,
                "question": question_obj.question,
                "marks": question_obj.marks,
                # instead of bringing answers data here, we make a function in Question model itself and call it here
                'answers': question_obj.get_ans()
            })
            
        payload = {'status': True, 'data': data}
        return JsonResponse(payload)
        
    except Exception as e:
        print(e)
    return HttpResponse("Something went wrong")

def take_quiz(request):
    context = {'categories': Category.objects.all(), 
               'questions': Question.objects.all(),
               'quizes': Quiz.objects.all()}
    
    # if request.GET.get('category'):
    #     return redirect(f"/quiz/?category={request.GET.get('category')}")
    
    return render(request, 'take_quiz.html', context)

def quiz(request):
    return render(request, 'quiz.html')


def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

quizes/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView
from django.http import JsonResponse, HttpResponse
from results.models import Result
from quiz.models import Question, Answer, Category
from .models import Quiz

from results.models import Result

from tablib import Dataset
import pandas as pd
from .forms import UploadCSVForm



# Quiz List view
class QuizListView(ListView):
    model = Quiz
    template_name = 'quizes/main.html'
    # return render(request, 'quizes/main.html', context)
    

class QuizDetailView(DetailView):
    model = Quiz
    template_name = 'quizes/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        quiz = self.get_object()  # Get the quiz object
        # Get the result for the current user and quiz, if exists
        result = Result.objects.filter(quiz=quiz, user=self.request.user).first()
        context['result'] = result  # Add the result to the context
        return context
    

# def quiz_detail_data_view(request, pk):
#     quiz = Quiz.objects.get(pk=pk)
#     questions = []
#     for question in quiz.get_questions:
#         answers = []
#         for answer in question.get_answers:
#             answers.append(answer.text)
#         questions.append({question.text: answers})
    
#     return JsonResponse({
#         'data': questions,
#         'time': quiz.time
#     })
    

def quiz_detail_data_view(request, pk):
    quiz = Quiz.objects.get(pk=pk)
    questions = []

    for question in quiz.get_questions:
        answers = []
        for answer in question.question_answer.all():  # Access related Answer objects using 'question_answer'
            answers.append(answer.answer)
        questions.append({question.question: answers})
    
    return JsonResponse({
        'data': questions,
        'time': quiz.time
    })


# def save_quiz_view(request, pk):
#     if request.accepts("application/json"):
#         data = request.POST
#         data_ = dict(data.lists())
#         data_.pop('csrfmiddlewaretoken')

#         questions = []

#         for k in data_.keys():
#             question = Question.objects.get(text=k)
#             questions.append(question)

#         user = request.user
#         quiz = Quiz.objects.get(pk=pk)

#         required_score = quiz.required_score
#         score = 0
#         multiplier = 100 / len(questions) 
#         results = []

#         for q in questions:
#             a_selected = data[q.text]

#             if a_selected != '':
#                 correct_answer = Answer.objects.filter(question=q).get(correct=True)
#                 if a_selected == correct_answer.text:
#                     score += 1
                
#                 results.append({q.text: {
#                     'correct_answer': correct_answer.text,
#                     'answered': a_selected
#                 }})
#             else:
#                 results.append({q.text: 'not answered'})

#         final_score = score * multiplier


#         Result.objects.create(quiz=quiz, user=user, score=final_score)

#         json_response = {
#             'score': final_score,
#             'correct_questions': score,
#             'passed': False,
#             'required_score': required_score,
#             'results': results
#         }

#         if final_score >= required_score:
#             json_response['passed'] = True
#             return JsonResponse(json_response)    

#         return JsonResponse(json_response)


def save_quiz_view(request, pk):
    if request.accepts("application/json"):
        data = request.POST
        data_ = dict(data.lists())
        data_.pop('csrfmiddlewaretoken')

        questions = []

        for k in data_.keys():
            # Since 'k' represents the question text, we need to filter questions by 'question' field
            question = Question.objects.get(question=k)  # Adjusted to match the 'question' field
            questions.append(question)

        user = request.user
        quiz = Quiz.objects.get(pk=pk)

        required_score = quiz.required_score
        score = 0
        multiplier = 100 / len(questions)
        results = []

        for q in questions:
            # Adjusted to match the 'question' field
            a_selected = data[q.question] if q.question in data else ''

            if a_selected != '':
                # Filter answers by 'answer' field
                correct_answer = Answer.objects.filter(question=q, is_correct=True).first()
                if correct_answer and a_selected == correct_answer.answer:
                    score += 1

                results.append({q.question: {
                    'correct_answer': correct_answer.answer if correct_answer else '',  # Adjusted to match the 'answer' field
                    'answered': a_selected
                }})
            else:
                results.append({q.question: 'not answered'})

        final_score = score * multiplier

        Result.objects.create(quiz=quiz, user=user, score=final_score)

        json_response = {
            'score': final_score,
            'correct_questions': score,
            'passed': False,
            'required_score': required_score,
            'results': results
        }

        if final_score >= required_score:
            json_response['passed'] = True
            return JsonResponse(json_response)

        return JsonResponse(json_response)

# views.py

# def upload_quiz(request):
#     if request.method == 'POST' and request.FILES['csv_file']:
#         csv_file = request.FILES['csv_file']
#         # file_path = csv_file.temporary_name()
#         csv_data = io.BytesIO(csv_file.read())
#         # Process the CSV file
#         process_csv_file(csv_data)
#         return render(request, 'quizes/success.html')
#     return render(request, 'quizes/upload_quiz.html')

# def upload_quiz(request):
#     if request.method == 'POST' and request.FILES['csv_file']:
#         csv_file = request.FILES['csv_file']
#         csv_data = csv_file.read().decode('utf-8')  # Read content as text

#         try:
#             process_csv_file(csv_data)  # Pass the data directly
#             return render(request, 'quizes/success.html')
#         except Exception as e:
#             # Handle any errors
#             return HttpResponse(f'<h1>Error {e}</h1>')

#     return render(request, 'quizes/upload_quiz.html')



# def process_csv_file(csv_file):
#     reader = csv.DictReader(csv_file)
#     for row in reader:
#         # Create or get category
#         category, created = Category.objects.get_or_create(category_name=row['Category'])
#         # Create or get quiz
#         quiz, created = Quiz.objects.get_or_create(
#             name=row['Quiz'],
#             category=category,
#             time=row['Time'],
#             required_score=row['Required Score'],
#             difficulty=row['Difficulty']
#         )
#         # Create question
#         question = Question.objects.create(
#             quiz=quiz,
#             question=row['Question'],
#             marks=row['Marks']
#         )
#         # Create answer
#         answer = Answer.objects.create(
#             question=question,
#             answer=row['Answer'],
#             is_correct=True if row['Is Correct'] == 'True' else False
#         )

def upload_quiz(request):
    if request.method == 'POST':
        form = UploadCSVForm(request.POST, request.FILES)
        if form.is_valid():
            csv_file = request.FILES['csv_file']
            process_csv_file(csv_file)
            return render(request, 'quizes/success.html')
    else:
        form = UploadCSVForm()
    return render(request, 'quizes/upload_quiz.html', {'form': form})

def process_csv_file(csv_file):
    dataset = Dataset()
    imported_data = dataset.load(csv_file.read().decode('utf-8'), format='csv')
    
    for row in imported_data:
        category_name = row[1]  # Assuming 'Category' is at index 1
        category, created = Category.objects.get_or_create(category_name=category_name)
        
        quiz, created = Quiz.objects.get_or_create(
            name=row[0],  # Assuming 'Quiz' is at index 0
            category=row[1],
            time=row[7],  # Assuming 'Time' is at index 6
            required_score=row[8],  # Assuming 'Required Score' is at index 7
            number_of_questions=row[9],  # Assuming 'Number of Questions' is at index 8
            difficulty=row[6]  # Assuming 'Difficulty' is at index 5
        )
        
        question = Question.objects.create(
            quiz=quiz,
            question=row[2],  # Assuming 'Question' is at index 2
            marks=row[5]  # Assuming 'Marks' is at index 4
        )
        
        answer = Answer.objects.create(
            question=question,
            answer_text=row[3],  # Assuming 'Answer' is at index 3
            is_correct=True if row[4] == 'Yes' else False  # Assuming 'Is Correct' is at index 4
        )

# def upload_quiz(request):
#     if request.method == 'POST' and request.FILES['csv_file']:
#         csv_file = request.FILES['csv_file']
#         # Process the CSV file
#         process_csv_file(csv_file)
#         return render(request, 'quizes/success.html')
#     return render(request, 'quizes/upload_quiz.html')

# def process_csv_file(csv_file):
#     csv_data = csv_file.read().decode('utf-8')
#     reader = csv.DictReader(StringIO(csv_data))
    
#     for row in reader:
#         # print(row.keys())
#         # Create or get category
#         category, created = Category.objects.get_or_create(category_name=row['category_name'])
#         # Create or get quiz
#         quiz, created = Quiz.objects.get_or_create(
#             name=row['quiz_name'],
#             category=category,
#             time=row['time'],
#             required_score=row['required_score'],
#             difficulty=row['difficulty']
#         )
#         # Create question

quizes/templates/quizes/detail.html
{% extends 'index.html' %}

{% block title %}{{object.name}}{% endblock title %}

{% comment %} {% block scripts %}
<script src="{% static 'quiz/quizes/quiz.js' %}" defer></script>
{% endblock scripts %} {% endcomment %}

{% comment %} {% with already_submitted = 0 %}
    {% for r in result %}
        {% if r.quiz == quiz.name %}
            {% with already_submitted = 1 %}
            {% endwith %}
        {% endif %}
    {% endfor %}
{% endwith %} {% endcomment %}

{% block content %}
{% comment %} {% for r in result %}
    {% if r.quiz == quiz.name %}
        temp = 1
        break
    {% endif %}
{% endfor %} {% endcomment %}

{% if result %}
    <div class="quiz_container">
        <h1>Already Submitted</h1>
    <div>

        <div class="py-3">
            <a href="{% url 'quizes:quiz_list_view' %}" class="btn btn-danger" id="">
                Go back
            </a>
        </div>
{% else %}
    <div class="quiz_container">
        <div class="container text-center py-4">
            <h1 class="">Quiz: {{object.name}}</h1>
            <p>
                {% for r in Result %}
                {% if r.quiz == quiz.name %}
                    {{r.score}}
                {% endif %}
            {% endfor %}
        </p>
        </div>
        
        <div class="row">
            <div class="col">
                <div class="text-secondary my-auto" id="score-box">
                    <p>Required score: {{object.required_score}} %</p>
                </div>
            </div>
            <div class="col text-end" id="timer-box">
                {{quiz.time}}
            </div>
        </div>
        
        <div class="py-3">
            
        </div>
        
        <form class="mt-3" id="quiz-form">
            {% csrf_token %}
            <div id="quiz-box" class="">
            </div>
            <div class="text-center py-3">
                <button type="submit" class="mt-4 btn btn-primary btn-lg">Send</button>
                <button class="mt-4 btn btn-danger btn-lg"><a href="{% url 'quizes:quiz_list_view' %}">
                    Go back
                </a></button>
                
            </div>
        </form>
        
        <div id="result-box">
        
        </div>
    </div>
{% endif %}

{% endblock content %}

quizes/templates/quizes/main.html
{% extends 'index.html' %}
{% load static %}


{% comment %} {% block scripts %}
<script src="{% static 'quiz/quizes/quizes.js' %}" defer></script>
{% endblock scripts %} {% endcomment %}


{% block title %}Home{% endblock title %}

{% block content %}

<div class="quiz_list_container">
    <!-- Modal -->
<div class="modal fade" id="quizStartModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Start Quiz</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body" id="modal-body-confirm">
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-danger" data-bs-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-success" id="start-button">Start</button>
            </div>
        </div>
    </div>
</div>

<div class="">
    <h1 class="h1">
        Available Quizzes
    </h1>
</div>

<hr>

{% for object in object_list %}
<div class="m-3">

    <button type="button" class="quiz-name btn btn-link modal-button" data-pk="{{object.pk}}" data-date="{{object.date}}"
        data-name="{{object.name}}" data-description="{{object.description}}" data-topic="{{object.category}}"
        data-questions="{{object.number_of_questions}}" data-difficulty="{{object.difficulty}}"
        data-time="{{object.time}}" data-pass="{{object.required_score}}" data-bs-toggle="modal"
        data-bs-target="#quizStartModal">
        {{object.name}}
    </button>
</div>
{% endfor %}
</div>



{% endblock content %}

quizes/templates/quizes/success.html
{% extends 'index.html' %}
{% load static %}


{% block scripts %}
{% endblock scripts %}


{% block title %}Home{% endblock title %}

{% block content %}


    <h1>Uploaded</h1>


{% endblock content %}

quizes/templates/quizes/upload_quiz.html
{% extends 'index.html' %}

{% block content %}


    <h1>Upload Quiz</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit">Upload</button>
    </form>



{% endblock content %}